version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bticketing
      MYSQL_USER: user
      MYSQL_PASSWORD: MyPassword123!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis-main:
    image: redis:6.0
    container_name: redis-main
    restart: always
    ports:
      - "6380:6379" # 내부 Redis 포트를 6380에 매핑

  redis-queue:
    image: redis:6.0
    container_name: redis-queue
    restart: always
    ports:
      - "6379:6379" # 기본 포트 6379 사용
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
volumes:
  mysql-data:
