spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bticketing
    username: user
    password: MyPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
